# Generated by Django 4.2.2 on 2023-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exelgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xlmodel',
            name='exel_field',
        ),
        migrations.AddField(
            model_name='xlmodel',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xlmodel',
            name='name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
